language: ruby

rvm:
  - 2.6.0
  - 2.5.3
  - 2.4.5
  - 2.3.8
  - ruby-head
  - jruby-9.2.0.0
  # - rbx-3

gemfile:
  - gemfiles/active_record_52.gemfile
  - gemfiles/active_record_51.gemfile
  - gemfiles/active_record_50.gemfile
  - gemfiles/active_record_42.gemfile
  - gemfiles/active_record_41.gemfile
  - gemfiles/active_record_edge.gemfile

env:
  - DB=sqlite3
  - DB=postgresql
  - DB=mysql

sudo: false

before_install:
  - gem update --system
  - gem install bundler
script: 'bundle exec rake test'

cache: bundler

matrix:
  exclude:
    - rvm: 2.6.0
      gemfile: gemfiles/active_record_42.gemfile
    - rvm: 2.6.0
      gemfile: gemfiles/active_record_41.gemfile
    - rvm: 2.5.3
      gemfile: gemfiles/active_record_42.gemfile
    - rvm: 2.5.3
      gemfile: gemfiles/active_record_41.gemfile
    - rvm: 2.4.5
      gemfile: gemfiles/active_record_42.gemfile
    - rvm: 2.4.5
      gemfile: gemfiles/active_record_41.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/active_record_42.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/active_record_41.gemfile
  include:
    - rvm: 2.2.10
      gemfile: gemfiles/active_record_51.gemfile
      env: DB=sqlite3
    - rvm: 2.1.10
      gemfile: gemfiles/active_record_42.gemfile
      env: DB=sqlite3
    - rvm: 2.0.0
      gemfile: gemfiles/active_record_42.gemfile
      env: DB=sqlite3
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-9.2.0.0
    # - rvm: rbx-3
    - gemfile: gemfiles/active_record_edge.gemfile
  fast_finish: true
