language: ruby

rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.5
  - 2.3.1
  - ruby-head
  - jruby-1.7.26
  - jruby-9.1.5.0
  - rbx-3

gemfile:
  - gemfiles/active_record_41.gemfile
  - gemfiles/active_record_42.gemfile
  - gemfiles/active_record_50.gemfile
  - gemfiles/active_record_edge.gemfile

sudo: false

services: mongodb

script: "bundle exec rake spec"

cache: bundler

matrix:
  exclude:
    - rvm: 2.0.0
      gemfile: gemfiles/active_record_50.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/active_record_50.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/active_record_edge.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/active_record_edge.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/active_record_41.gemfile
    - rvm: jruby-1.7.26
      gemfile: gemfiles/active_record_50.gemfile
    - rvm: rbx-3
      gemfile: gemfiles/active_record_50.gemfile
    - rvm: jruby-1.7.26
      gemfile: gemfiles/active_record_edge.gemfile
    - rvm: rbx-3
      gemfile: gemfiles/active_record_edge.gemfile
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-1.7.26
    - rvm: jruby-9.1.5.0
    - rvm: rbx-3
  fast_finish: true
